import assert from "node:assert/strict";
import * as THREE from "three";
import { createImpactLights } from "./impactLights";

const scene = new THREE.Scene();
const camera = new THREE.PerspectiveCamera(60, 1, 1, 1500);
camera.position.set(0, 80, 100); camera.lookAt(0, 0, 0); camera.updateMatrixWorld();
const fx = createImpactLights(scene, camera);
const lights = scene.children as THREE.PointLight[];
assert.equal(lights.length, 2);
assert.ok(lights.every(l => !l.castShadow && l.intensity === 0));
fx.flash(0, 0);
assert.equal(lights.filter(l => l.intensity > 0).length, 1);
fx.flash(2, 2);
assert.equal(lights.filter(l => l.intensity > 0).length, 1, "nearby sub-bursts share a light");
fx.flash(40, 0);
assert.equal(lights.filter(l => l.intensity > 0).length, 2);
for (let i = 0; i < 100; i++) fx.flash(i % 50, 0);
assert.equal(scene.children.length, 2, "burst storms do not allocate more lights");
fx.update(80);
assert.ok(lights.every(l => l.intensity <= 400));
fx.update(1000);
assert.ok(lights.every(l => l.intensity === 0 && l.visible), "zero intensity preserves the shader light count");
fx.flash(0, 10000);
assert.ok(lights.every(l => l.intensity === 0), "offscreen lights consume no slots");
fx.flash(NaN, 0);
fx.dispose(); fx.dispose(); fx.flash(0, 0); fx.update(0);
assert.equal(scene.children.length, 0);
console.log("impact lights: bounded pool, merge, decay, culling and disposal ok");
