import assert from "node:assert/strict";
import * as THREE from "three";
import { getAuthoritativeShipHullProfile } from "@battlefleet/shared";
import { createBowFoam } from "./bowFoam";
import type { ShipVisual } from "./shipVisual";

const scene = new THREE.Scene(), texture = new THREE.Texture();
let textureDisposed = false;
texture.addEventListener("dispose", () => { textureDisposed = true; });
const foam = createBowFoam(scene, texture);
const group = new THREE.Group(); group.scale.x = -1; group.updateMatrixWorld(true);
const visual = { group, profile: getAuthoritativeShipHullProfile("fac") } as ShipVisual;
foam.begin(1); foam.add(visual, 0); foam.end();
assert.equal(scene.children.length, 0);
foam.begin(2);
for (let i = 0; i < 100; i++) foam.add(visual, 28);
foam.end();
assert.equal(scene.children.length, 1, "all bows share one mesh");
const mesh = scene.children[0] as THREE.Mesh;
assert.equal(mesh.geometry.drawRange.count, 64 * 72, "hard capacity bounds geometry");
const position = mesh.geometry.getAttribute("position"), buffer = position.array;
const firstX = position.getX(0), firstZ = position.getZ(0);
group.position.set(100, 0, -50); group.updateMatrixWorld(true);
foam.begin(3); foam.add(visual, 28); foam.end();
assert.equal(position.array, buffer);
assert.ok(Math.abs(position.getX(0) - firstX - 100) < 1e-4);
assert.ok(Math.abs(position.getZ(0) - firstZ + 50) < 1e-4);
assert.equal(mesh.geometry.drawRange.count, 72, "unused capacity is not drawn");
foam.begin(4); foam.end(); assert.equal(scene.children.length, 0);
foam.dispose(); foam.dispose(); foam.begin(5); foam.add(visual, 28); foam.end();
assert.equal(scene.children.length, 0);
assert.equal(textureDisposed, false, "shared texture belongs to the wake system");
texture.dispose();
console.log("bow foam: fixed capacity/buffers, one batch, transformed positions and resource ownership ok");
