import * as R from "@battlefleet/shared/rules";
import "./manual.css";

const classes: R.ShipClassId[] = ["fac", "destroyer", "cruiser"];
const names = { fac: "FAC · Gepard", destroyer: "Destroyer · Spruance", cruiser: "Cruiser" };
const fmt = (n: number, digits = 0) => n.toLocaleString("en-US", { maximumFractionDigits: digits });
const deg = (n: number) => n * 180 / Math.PI;
const table = (headers: string[], rows: (string | number)[][]) => `<div class="table-wrap"><table><thead><tr>${headers.map(h => `<th scope="col">${h}</th>`).join("")}</tr></thead><tbody>${rows.map(row => `<tr>${row.map(c => `<td>${c}</td>`).join("")}</tr>`).join("")}</tbody></table></div>`;
const titles = [["start", "01 · Getting started"], ["controls", "02 · Controls"], ["ships", "03 · Ship classes"], ["sectors", "04 · Firing sectors"], ["guns", "05 · Artillery"], ["missiles", "06 · Anti-ship missiles"], ["defense", "07 · Missile defense"], ["sensors", "08 · Radar & fire control"], ["progression", "09 · Score & progression"], ["survival", "10 · Survival & tactics"], ["faq", "11 · FAQ & glossary"]];
const section = (id: string, title: string, body: string) => `<section id="${id}"><h2>${title}</h2>${body}</section>`;
const hull = (id: R.ShipClassId) => R.getAuthoritativeShipHullProfile(id)!;
const sectorText = (sector: R.MountFireSector) => R.flattenMountFireSectorUnions(sector).map(s => {
  const arc = R.mountFireSectorArc(s);
  const wrap = (a: number) => fmt(deg(R.wrapPi(a)));
  return `${wrap(arc.start)}° to ${wrap(arc.start + arc.sweep)}° (${fmt(deg(arc.sweep))}° coverage)`;
}).join("; ");
const weaponNames: Record<R.WeaponSystemId, string> = { artillery: "Artillery", ciws: "CIWS · Close-in defense", sam: "SAM · Air defense", pdms: "PDMS · Point defense", ssm: "SSM · Anti-ship missile", torpedo: "Torpedo" };
document.querySelector<HTMLDivElement>("#manual")!.innerHTML = `<div class="layout"><nav aria-label="Table of contents"><strong>ON BOARD</strong>${titles.map(([id, name]) => `<a href="#${id}">${name}</a>`).join("")}</nav><main id="inhalt"><div class="eyebrow">SEA CONTROL: ARENA · PLAYER MANUAL</div><h1>Your ship.<br>Your battle.</h1><p class="lead">From your first turn to a coordinated missile attack: controls, game mechanics and technical data in one reference.</p><div class="note">This manual describes the <strong>game values in this build</strong>. Ranges, speeds, collision boxes and weapons are not historical ship specifications. Tables and sector diagrams use the bundled game rules directly. Servers may override settings such as round duration and scoring.</div>
${section("start", "Ready for action in one minute", `<ol><li><strong>Get moving:</strong> Use W/S for throttle and A/D for rudder. Your ship has inertia, so plan turns and stopping distances ahead.</li><li><strong>Find a target:</strong> Watch the contact display. F assigns the nearest eligible contact to fire control; R cycles through contacts in range. Manual fire control reaches ${R.FIRE_CONTROL_TARGET_RANGE} m.</li><li><strong>Set up your shot:</strong> Close to within ${R.ARTILLERY_RANGE} m for artillery and bring the target into the gun's firing sector. Aim with the mouse and fire with the left mouse button or Space.</li><li><strong>Earn points:</strong> Sink opponents and stay in the central Sea Control zone. Survival pays off: experience improves your ship and unlocks larger classes.</li></ol><p>A standard round lasts ${R.MATCH_DURATION_SEC / 60} minutes. You command one ship in a live arena. Opening the help menu or this page does not pause online play. Read longer sections before entering combat.</p>`)}
${section("controls", "Controls and displays", table(["Input", "Effect and use"], [
 ["<kbd>W</kbd> / <kbd>S</kbd>", "Control ahead / astern throttle. In step mode, move through throttle settings and neutral; momentum does not disappear immediately."],
 ["<kbd>A</kbd> / <kbd>D</kbd>", "Apply port / starboard rudder. Response depends on speed and ship class."],
 ["<kbd>M</kbd>", "Switch between hold and step steering. Check the active mode in the HUD."],
 ["Mouse", "Choose an aiming direction or impact point on the water."],
 ["Left mouse / <kbd>Space</kbd>", "Fire artillery. Holding the input fires again as the weapon becomes ready."],
 ["Right mouse", "Launch an anti-ship missile. An available launch rail is selected based on your aim direction."],
 ["<kbd>Q</kbd> / <kbd>E</kbd>", "Launch explicitly from the port / starboard missile rail."],
 ["<kbd>F</kbd>", "Select the nearest eligible contact within fire-control range."],
 ["<kbd>R</kbd>", "Cycle through contacts within fire-control range."],
 ["<kbd>C</kbd>", "Clear the fire-control target. This releases the assignment; it does not recall weapons already in flight."],
 ["RADAR button", "Toggle active search radar. R cycles contacts instead."],
 ["⛶ beside TAC", "Toggle browser fullscreen when supported. Escape can leave fullscreen."],
 ["Controls / Open full guide", "Show or hide the key reference at the bottom right, or open the quick guide."]
 ]) + `<p><strong>Port</strong> is left when facing forward; <strong>starboard</strong> is right. The bow is the front and the stern is the rear. These directions refer to your ship, not the edges of the screen. A small frame on the radar marks your assigned fire-control contact.</p><p>In hold mode, movement inputs act while their keys are held. Step mode lets you select persistent throttle and rudder settings. Check both indicators when changing modes. On mobile, use the on-screen controls: <strong>Next target</strong> cycles contacts, <strong>Nearest target</strong> selects the closest eligible contact within 800 m, and <strong>Clear target</strong> releases fire control so you can aim freely.</p>`)}
${section("ships", "Three classes, three ways to fight", `<div class="grid"><article class="card"><h3>FAC · Gepard class</h3><p>Your fast starting boat at levels 1–2. Its strength is repositioning: reach the zone early, find a useful firing angle and withdraw before a prolonged exchange.</p><p>Low durability leaves little room for mistakes. Forward artillery is backed by a stern-oriented point-defense system. Both SSM rails point diagonally forward; a target directly ahead is not automatically inside either initial seeker cone.</p></article><article class="card"><h3>Destroyer · Spruance class</h3><p>At levels 3–4 you receive a more versatile destroyer. More HP and missiles support longer engagements, but its larger silhouette and lower speed require earlier maneuver planning.</p><p>Artillery and CIWS mainly cover the forward area, while SAM covers the rear. SSMs launch sideways: align the appropriate broadside with the expected target position.</p></article><article class="card"><h3>Cruiser</h3><p>From level 5, the cruiser provides a large missile magazine and high durability for holding the zone. This is a game cruiser profile, not a claim to represent a specific historical class.</p><p>Lower speed and a large collision box make narrow island passages risky. Its SSM rails point almost forward. Planning ahead matters more than last-second evasive turns.</p></article></div><h3>Base specifications before level bonuses</h3>${table(["Property", ...classes.map(id => names[id])], [
 ["Collision box L × W × H (game meters)", ...classes.map(id => { const b = hull(id).collisionHitbox?.halfExtents; return b ? `${fmt(b.z * 2)} × ${fmt(b.x * 2)} × ${fmt(b.y * 2)} m` : "Not defined"; })],
 ["Base HP", ...classes.map(id => R.getShipClassProfile(id).baseMaxHp)],
 ["Displayed top speed", ...classes.map(id => `${fmt(R.movementConfigForPlayer(R.DESTROYER_LIKE_MVP, R.getShipClassProfile(id), 1, hull(id).movement).maxSpeed / R.SPEED_FEEL_FACTOR, 1)} kn`)],
 ["Maximum turn rate¹", ...classes.map(id => `${fmt(deg(R.movementConfigForPlayer(R.DESTROYER_LIKE_MVP, R.getShipClassProfile(id), 1, hull(id).movement).maxTurnRateRad), 1)} °/s`)],
 ["Incoming weapon damage²", ...classes.map(id => `${fmt(R.getShipClassProfile(id).incomingDamageTakenMul * 100)} %`)],
 ["SSM port + starboard", ...classes.map(id => { const m = R.getAswmMagazineFromProfile(hull(id), id); return `${m.port} + ${m.starboard}`; })],
 ["SSM magazine reload", ...classes.map(id => `${R.getAswmMagicReloadMsFromProfile(hull(id)) / 1000} s`)],
 ["Maximum active own SSMs", ...classes.map(id => R.getShipClassProfile(id).aswmMaxPerOwner)],
 ])}<p class="muted">¹ Upper limit at sufficient speed and full rudder, not a fixed turning circle. ² Class multiplier before other progression and damage rules; below 100% means less incoming weapon damage. The knot display uses game scaling, not a physical conversion from simulation meters per second.</p><p>Level bonuses are added to these base values. A normally unlocked destroyer therefore starts stronger than a hypothetical level-1 destroyer. The explorer below uses the actual class associated with each level.</p>`)}
${section("sectors", "Ship and firing-sector explorer", `<p>Select a level and weapon. The colored area shows its angular coverage. Move the target-bearing slider to see whether that direction lies inside the sector.</p><div class="controls"><label>Level and ship<select id="level">${Array.from({length:10}, (_, i) => `<option value="${i + 1}">Level ${i + 1} · ${names[R.shipClassIdForProgressionLevel(i + 1)]}</option>`).join("")}</select></label><label>Weapon system<select id="weapon"></select></label><label>Target bearing from bow<input id="bearing" type="range" min="-180" max="180" value="60" step="1"><output id="bearing-value" for="bearing"></output></label></div><div class="explorer"><div id="diagram"></div><div><div id="stats" class="stats"></div><div id="sector-result" class="result" role="status"></div><p class="muted">0° = bow · +90° = starboard · ±180° = stern · −90° = port. Yellow marks the selected bearing. The diagram is not to scale; sectors start at the ship's center for clarity.</p></div></div><div class="note">This check evaluates <strong>angle only</strong>. Range, islands, readiness, ammunition and target state can still prevent a shot. For SSMs, the fan shows the seeker angle relative to the launch direction. The rail itself is fixed and does not turn toward the target.</div><h3>Installed systems and sectors</h3>${table(["Ship", "System", "Angle relative to bow", "Range"], classes.flatMap(id => {
 const h = hull(id); return h.mountSlots.flatMap(slot => { const e = R.equippedMount(slot, h); return e ? [[names[id], weaponNames[e.weaponId], sectorText(R.resolveEffectiveMountFireSector(slot, h, R.getShipClassProfile(id).artilleryArcHalfAngleRad)), `${R.weaponSystem(e.weaponId).engagementRange} m`]] : []; });
 }))}<p>A stern-facing sector crosses the +180°/−180° boundary. For example, a 240° stern sector covers both sides of the stern while leaving a forward wedge uncovered. A model slot's internal name does not determine its function: the weapon actually fitted to it does.</p>`)}
${section("guns", "Artillery: range, lead and timing", `<p>Artillery is your direct, repeatable weapon against ships. It fires at a calculated impact point. A visible or assigned contact must also be within range and inside the firing sector. All three current hulls carry their main gun forward.</p>${table(["Parameter", "Game value"], [["Maximum range", `${R.ARTILLERY_RANGE} m`], ["Base damage", R.ARTILLERY_DAMAGE], ["Blast radius", `${R.ARTILLERY_SPLASH_RADIUS} m`], ["Base firing interval", `${R.ARTILLERY_PRIMARY_COOLDOWN_MS} ms`], ["Angular spread", `±${fmt(deg(R.ARTILLERY_SPREAD_HALF_ANGLE_RAD))}°`], ["Distance spread", `±${R.ARTILLERY_SPREAD_DIST_FACTOR * 100} %`], ["Flight time", `${R.ARTILLERY_FLIGHT_TIME_BASE_MS} ms + distance × ${R.ARTILLERY_FLIGHT_TIME_PER_UNIT_MS} ms/m, capped at ${R.ARTILLERY_FLIGHT_TIME_MAX_MS} ms`]])}<p><strong>Lead your target:</strong> Your opponent keeps moving while the shell is airborne. Aim ahead in its direction of travel. A ship crossing your line of sight needs more sideways lead than one approaching directly. A course change after firing can cause a miss, and spread makes occasional misses normal.</p><p><strong>Firing position:</strong> With your stern toward an opponent, the forward gun cannot simply fire through your superstructure. Turn until the target enters its sector. Island cover and the range limit still matter. A fire-control contact at 700 m is not an artillery target within 300 m.</p><p><strong>Damage and readiness:</strong> Base damage is not a guaranteed HP reduction. Impact position, blast calculations and defensive modifiers affect the result. Higher levels shorten the firing interval. A valid target indicator therefore does not necessarily mean the gun has finished reloading.</p>`)}
${section("missiles", "SSMs: launch rails and seekers", `<p>SSMs (surface-to-surface missiles), also called ASWM in the code, attack ships. They leave a fixed rail and then autonomously search for a suitable target ahead of their flight direction. Clicking a ship or assigning fire control does not guarantee that this particular ship will be hit.</p>${table(["Parameter", "Game value"], [["Speed", `${R.ASWM_SPEED} simulation m/s`], ["Lifetime", `${R.ASWM_LIFETIME_MS / 1000} s`], ["Theoretical straight flight distance", `${R.ASWM_SPEED * R.ASWM_LIFETIME_MS / 1000} m`], ["Base damage", R.ASWM_DAMAGE], ["Minimum launch interval", `${R.ASWM_SHOT_INTERVAL_MS / 1000} s`], ["Seeker activation", `${R.ASWM_SEEKER_ARM_DELAY_MS} ms after launch`], ["Seeker cone", `±${fmt(deg(R.ASWM_ACQUIRE_HALF_ANGLE_RAD))}°; ${R.ASWM_ACQUIRE_CONE_LENGTH} m long`], ["Maximum turn rate", `${fmt(deg(R.ASWM_TURN_RATE_RAD_PER_S), 1)} °/s`]])}<p>The theoretical flight distance is <strong>not a guaranteed acquisition range</strong>. Turns, obstacles, defense and lifetime limit the attack. The seeker cone starts at the missile, not at your ship. During the first ${R.ASWM_SEEKER_ARM_DELAY_MS} ms, the seeker is inactive; a missile flying straight covers about ${R.ASWM_SPEED * R.ASWM_SEEKER_ARM_DELAY_MS / 1000} m in that time.</p><h3>Choose the right launch angle</h3>${table(["Ship", "Fixed launch angles"], classes.map(id => [names[id], (hull(id).fixedSeaSkimmerLaunchers ?? []).map(l => `${fmt(deg(R.launcherYawRadFromBow(l)))}°`).join(" / ")]))}<p>Destroyer missiles launch sideways. An opponent directly ahead may initially lie outside the search cone. Align the appropriate side with the expected target position and remember that both ships keep moving. FAC and cruiser rails use different angles, so a successful launch technique does not transfer unchanged between classes.</p><h3>Magazine reload, not individual missile reload</h3><p>Port and starboard have separate ammunition stocks. If one side is empty, the other can still fire. The full magazine reload starts only when all rounds have been expended. Reload duration depends on the hull. The minimum launch interval and maximum number of active own missiles also limit output. Plan for the long pause after a complete salvo.</p><p><strong>Tactical use:</strong> Choose your course and launch side before firing. Several missiles arriving close together can put pressure on repeated defensive attempts, but do not guarantee a breakthrough. Avoid launching into an island or along a path where the seeker is unlikely to encounter the target.</p>`)}
${section("defense", "Automatic missile defense", `<p>Installed defensive systems automatically engage eligible incoming missiles. SAM, PDMS and CIWS are not fired with your primary-fire input. Your contribution is positioning: nominal range cannot compensate for an incoming threat being outside a weapon's sector.</p>${table(["System", "Range", "Base interval", "Chance per attempt"], [["SAM", `${R.weaponSystem("sam").engagementRange} m`, `${R.AD_SAM_COOLDOWN_MS / 1000} s`, `${R.AD_SAM_P_HIT * 100} %`], ["PDMS", `${R.weaponSystem("pdms").engagementRange} m`, `${R.AD_PD_COOLDOWN_MS / 1000} s`, `${R.AD_PD_P_HIT * 100} %`], ["CIWS", `${R.weaponSystem("ciws").engagementRange} m`, `${R.AD_CIWS_COOLDOWN_MS / 1000} s`, `${fmt(R.AD_CIWS_P_HIT * 100)} %`]])}<p>These percentages apply to one valid interception attempt, not the overall probability of surviving a missile attack. The number of attempts depends on approach, distance, sector and readiness. SAM and PDMS also have interception travel time: triggering them does not instantly remove the threat.</p><p><strong>Softkill</strong> can break a missile's target lock. Standard rules use ${R.AD_SOFTKILL_RANGE} m range, a ${R.AD_SOFTKILL_PROC_CHANCE * 100}% chance and a ${R.AD_SOFTKILL_COOLDOWN_MS / 1000} s cooldown. After a successful break, reacquiring that same target is temporarily blocked. This does not guarantee destruction of the missile.</p><p>The FAC has stern-oriented point defense. Destroyers and cruisers combine forward CIWS with rear SAM coverage. Use the explorer to check which approach directions your installed systems can cover. A class's longest defensive range does not apply equally around the whole ship.</p>`)}
${section("sensors", "Detection, tracking and assignment", `<p><strong>Contact display:</strong> The display shows the tactical area out to ${R.SHIP_CONTACT_DISPLAY_RANGE} m. Its radius does not mean every opponent inside that circle is visible. Detection depends on sensor state, target class and distance.</p>${table(["Target class", "Active radar", "Passive sight, undamaged", "Passive sight, smoking"], classes.map(id => [names[id], `${fmt(R.radarDetectionRange(id))} m`, `${fmt(R.visualDetectionRange(id, 100, 100))} m`, `${fmt(R.visualDetectionRange(id, 50, 100))} m`]))}<p>The <strong>target's class</strong> determines class-dependent detection distances. Larger ships have greater radar and undamaged visual detection ranges. Ships emit damage smoke below ${R.DAMAGE_SMOKE_HP_RATIO * 100}% of maximum HP; the smoking-target sight range is shown separately above. Smoke affects detection rules, not just visual effects.</p><h3>Active radar and passive ESM</h3><p>Active radar reveals contacts within radar range, but also emits a signal that passive ESM can detect. ESM (Electronic Support Measures) provides information about emitters and their bearing; a bearing is not the same as a precise target contact. Emission detection range depends on the emitting class: ${classes.map(id => `${names[id]} ${fmt(R.esmDetectionRange(id))} m`).join(", ")}.</p><p>Switching radar off does not make you invisible. Passive sight and the visibility of a smoking hull still apply. Balance your own situational awareness against the information your emissions give away.</p><h3>Manual fire control</h3><p>F selects the nearest eligible contact within ${R.FIRE_CONTROL_TARGET_RANGE} m. R cycles through contacts in range; C clears the assignment. The selected contact has a small frame on the radar. The channel may be lost if the contact no longer meets the conditions. Assignment helps you aim; it does not fire automatically or extend weapon range.</p><div class="note">Example: radar may detect a cruiser at long range. It only becomes eligible for manual fire control within ${R.FIRE_CONTROL_TARGET_RANGE} m. Artillery still requires no more than ${R.ARTILLERY_RANGE} m and a valid firing angle. An SSM instead checks its own ${R.ASWM_ACQUIRE_CONE_LENGTH} m seeker cone during flight.</div>`)}
${section("progression", "Score, experience and class changes", `<p>Sinkings and recurring survival rewards drive progression during a round. A credited sinking grants ${R.PROGRESSION_XP_PER_KILL} XP by default. Passive rewards grant ${R.MATCH_PASSIVE_XP_BASE} XP every ${R.MATCH_PASSIVE_XP_INTERVAL_MS / 1000} seconds, multiplied by ${R.SEA_CONTROL_XP_MULTIPLIER} inside the Sea Control zone. These awards also increase the round score.</p><p>The central zone is a square ${R.SEA_CONTROL_ZONE_HALF_EXTENT * 2} m across. Stay inside it to receive the bonus; exclusive flag capture is not required. Multiple living ships can receive the zone bonus simultaneously. The center is worthwhile even without an immediate sinking, but remains a dangerous meeting point.</p>${table(["Level", "Minimum XP", "Rank", "Ship", "Maximum HP", "Gun interval"], Array.from({length:10}, (_, i) => { const lv = i + 1; const id = R.shipClassIdForProgressionLevel(lv); return [lv, R.progressionMinXpForLevel(lv), R.progressionNavalRankEn(lv), names[id], R.progressionMaxHpForLevel(lv, R.getShipClassProfile(id).baseMaxHp), `${R.progressionPrimaryCooldownMs(lv)} ms`]; }))}<p>Leveling up increases maximum HP and movement performance and improves the gun's firing interval. Additional maximum HP is accounted for when leveling up, but this is not a blanket full repair. Changing class also changes the hull, magazine and firing sectors. Pay particular attention to the Spruance's sideways SSM rails.</p><p>When sunk, you lose one level, down to a minimum of level 1. XP resets to that level's lower threshold; your earned round score remains separate. Progression starts again with a new round. Naval ranks represent game levels, not historical crew sizes or command structures.</p>`)}
${section("survival", "Survival, movement and tactical decisions", `<h3>Work with your ship's inertia</h3><p>High throttle gets you into position quickly but makes stopping in time more difficult. Rudder response builds up instead of instantly turning the hull toward the mouse. Full turn rate is unavailable at low speed. Astern speed is limited to a fraction of maximum forward speed. Narrow channels are therefore more demanding in a cruiser than in a FAC.</p><h3>Collisions and durability</h3><p>The visible hull is not the complete collision model. Physics uses simplified collision shapes. Island contact and collisions can cause damage, so leave clearance near shore. Class damage multipliers should not be interpreted as historical armor thicknesses.</p><p>Under current standard rules, living ships continuously regenerate 1% of maximum HP per second. Time away from concentrated fire can therefore help. After sinking, you respawn with a short protection phase. Watch your life state in the HUD; protection is not permission to ignore dangerous collisions.</p><h3>Three common situations</h3><ol><li><strong>Fast but fragile:</strong> Use the FAC to choose routes and angles. Avoid stationary close-range exchanges. Withdrawing early can be worth more than one last risky shot.</li><li><strong>Holding the center:</strong> Do not sail predictably through crossfire. Keep track of your artillery target, the nearest island and incoming missiles. Sustained zone rewards only help while you stay alive.</li><li><strong>Empty magazine:</strong> Keep your distance or use cover until reloading finishes. Artillery and automatic defense remain independent systems; an empty SSM magazine does not leave the whole ship defenseless.</li></ol><p>There is no single best heading. Artillery attacks, fixed launch rails and defensive sectors may call for different courses. Before turning, decide what matters most: a gunshot, a missile launch, protection against an incoming threat or a safe escape route.</p>`)}
${section("faq", "Frequently asked questions and glossary", `<details open><summary>Why will my gun not fire at a marked target?</summary><p>Check distance, firing sector, obstacles and reload time. Fire control reaches farther than artillery. A target frame alone does not confirm that a shot is possible.</p></details><details open><summary>Why does my missile fly past the enemy?</summary><p>The fixed rail may point the wrong way, the target may be outside the seeker cone when it activates, or the target may evade the missile's limited turn rate. Defenses and obstacles also affect its flight. Use the explorer to understand your current hull's launch angles.</p></details><details open><summary>Why are different ships visible at different distances?</summary><p>Radar and undamaged sight ranges depend on target class. Damage smoke uses its own visual detection range. Switching your radar off removes your active detection but does not remove other ships' passive sensing.</p></details><details open><summary>Why did my weapon angles change after leveling up?</summary><p>Levels 3 and 5 change your ship class. Each hull has its own equipment and fixed launch rails. A launch heading that worked before may no longer be suitable.</p></details><details open><summary>Are these real-world specifications?</summary><p>These are game parameters. Historical names and model references do not mean dimensions, performance or weapons exactly match a real ship. This manual does not add unsupported displacement, crew or engine-power figures.</p></details>${table(["Term", "Meaning"], [["FAC", "Fast Attack Craft: a small, fast attack boat."], ["SSM / ASWM", "Anti-ship missile: an offensive weapon against ships."], ["SAM", "Surface-to-Air Missile: used here for automatic missile defense."], ["PDMS", "Point Defense Missile System."], ["CIWS", "Close-In Weapon System: automatic short-range defense."], ["ESM", "Passive detection of electromagnetic emissions."], ["Firing sector", "Angular area within which a mounted weapon may engage."], ["Softkill / hardkill", "Break target lock / intercept the incoming missile."], ["HP / XP", "Hit points / experience points."], ["TAC", "Tactical display for situational awareness."]])}`)}
<footer>Sources: shared game rules, authoritative hull profiles and standard server behavior. Values apply to this page's build. The sector diagram needs neither WebGL nor a running game simulation. <a href="./">Back to game</a></footer></main></div>`;

const level = document.querySelector<HTMLSelectElement>("#level")!;
const weapon = document.querySelector<HTMLSelectElement>("#weapon")!;
const bearing = document.querySelector<HTMLInputElement>("#bearing")!;
type Choice = { name: string; sector: R.MountFireSector; range: string; rail?: number };
let choices: Choice[] = [];
function updateShip() {
 const lv = Number(level.value), id = R.shipClassIdForProgressionLevel(lv), h = hull(id), p = R.getShipClassProfile(id);
 const movement = R.movementConfigForPlayer(R.DESTROYER_LIKE_MVP, p, lv, h.movement);
 choices = h.mountSlots.flatMap(slot => { const e = R.equippedMount(slot, h); return e ? [{ name: weaponNames[e.weaponId], sector: R.resolveEffectiveMountFireSector(slot, h, p.artilleryArcHalfAngleRad), range: `${R.weaponSystem(e.weaponId).engagementRange} m range` }] : []; });
 for (const l of h.fixedSeaSkimmerLaunchers ?? []) { const yaw = R.launcherYawRadFromBow(l); choices.push({ name: `SSM rail ${fmt(deg(yaw))}°`, sector: { kind: "symmetric", halfAngleRadFromBow: R.ASWM_ACQUIRE_HALF_ANGLE_RAD, centerYawRadFromBow: yaw }, range: `${R.ASWM_ACQUIRE_CONE_LENGTH} m seeker cone from missile`, rail: yaw }); }
 weapon.innerHTML = choices.map((c, i) => `<option value="${i}">${c.name}</option>`).join("");
 document.querySelector("#stats")!.innerHTML = [[`${R.progressionMaxHpForLevel(lv, p.baseMaxHp)}`, "maximum HP"], [`${fmt(movement.maxSpeed / R.SPEED_FEEL_FACTOR, 1)} kn`, "displayed top speed"], [`${fmt(deg(movement.maxTurnRateRad), 1)} °/s`, "maximum turn rate"], [`${R.progressionPrimaryCooldownMs(lv)} ms`, "gun firing interval"]].map(([v, label]) => `<div><strong>${v}</strong><span>${label}</span></div>`).join("");
 draw();
}
function draw() {
 const c = choices[Number(weapon.value)]!; const a = Number(bearing.value) * Math.PI / 180;
 const point = (angle: number, radius = 137) => `${180 + Math.sin(angle) * radius},${180 - Math.cos(angle) * radius}`;
 const paths = R.flattenMountFireSectorUnions(c.sector).map(s => { const arc = R.mountFireSectorArc(s); const count = Math.max(2, Math.ceil(deg(arc.sweep))); return `<path d="M180,180 ${Array.from({length:count + 1}, (_, i) => `L${point(arc.start + arc.sweep * i / count)}`).join(" ")} Z" fill="#247f88" fill-opacity=".5" stroke="#63cfce"/>`; }).join("");
 const inside = R.isYawWithinMountFireSector(a, c.sector);
 document.querySelector("#bearing-value")!.textContent = `${bearing.value}°`;
 document.querySelector("#diagram")!.innerHTML = `<svg viewBox="0 0 360 360" role="img" aria-label="${c.name}: angular coverage and target bearing ${bearing.value} degrees"><circle cx="180" cy="180" r="137" fill="none" stroke="#405969"/><path d="M180 38V322M38 180H322" stroke="#405969" stroke-dasharray="3 6"/>${paths}${c.rail !== undefined ? `<path d="M180,180 L${point(c.rail)}" stroke="#b8edff" stroke-width="3"/>` : ""}<path d="M180 138L191 161L191 214L169 214L169 161Z" fill="#dce8f0" stroke="#09141f" stroke-width="2"/><path d="M180,180 L${point(a, 148)}" stroke="#ffce66" stroke-width="2"/><circle cx="${180 + Math.sin(a) * 148}" cy="${180 - Math.cos(a) * 148}" r="5" fill="#ffce66"/><g fill="#e1eaf0" font-size="11" text-anchor="middle"><text x="180" y="22">BOW · 0°</text><text x="180" y="346">STERN · 180°</text><text x="36" y="170">−90°</text><text x="325" y="170">+90°</text></g></svg>`;
 document.querySelector("#sector-result")!.textContent = `${inside ? "Inside" : "Outside"} ${c.rail !== undefined ? "the initial seeker cone" : "the firing sector"}. ${c.range}. ${sectorText(c.sector)}.`;
}
level.addEventListener("change", updateShip);
weapon.addEventListener("change", draw);
bearing.addEventListener("input", draw);
document.querySelector("#print")!.addEventListener("click", () => window.print());
updateShip();

