import assert from "node:assert/strict";
import { MATCH_PHASE_ENDED, MATCH_PHASE_RUNNING } from "@battlefleet/shared/rules";
import { MatchSystem } from "./MatchSystem.js";

const state = { matchPhase: MATCH_PHASE_RUNNING, matchRemainingSec: 999 };
let sequence = 0;
const match = new MatchSystem(state, () => `fixture-${++sequence}`);
match.start(1000, 2100, false);
assert.equal(match.matchId, "fixture-1");
assert.equal(state.matchRemainingSec, 999, "creation preserves default until first tick");
assert.equal(match.endsAtMs, 3100);
assert.equal(match.canRestart(false), false);
assert.equal(match.canRestart(true), true);
assert.equal(match.tick(1000), false);
assert.equal(state.matchRemainingSec, 3);
assert.equal(match.tick(3099), false);
assert.equal(state.matchRemainingSec, 1);
assert.equal(match.tick(3100), true);
assert.equal(state.matchPhase, MATCH_PHASE_ENDED);
assert.equal(state.matchRemainingSec, 0);
assert.equal(match.tick(5000), false, "end effects are requested only once");
assert.equal(match.tick(1000), false, "clock rollback cannot reopen an ended round");
assert.equal(match.canRestart(false), true);
match.start(5000, 2000, true);
assert.equal(match.matchId, "fixture-2", "reset allocates a distinct identity without consuming gameplay RNG");
assert.equal(state.matchPhase, MATCH_PHASE_RUNNING);
assert.equal(state.matchRemainingSec, 2);
assert.equal(match.tick(7000), true, "restart resets the exactly-once latch");
console.log("headless match deadline, restart and exactly-once transition ok");
