// Build-time teaching figures. Everything is embedded for offline use.
const fig = (id, title, body, caption) => `<figure class="teaching-figure" id="${id}"><h3>${title}</h3>${body}<figcaption>${caption}</figcaption></figure>`;
const flow = (items) => `<ol class="visual-flow">${items.map(([title, detail]) => `<li><strong>${title}</strong><span>${detail}</span></li>`).join('')}</ol>`;
const svg = (title, body) => `<svg class="lesson-svg" viewBox="0 0 320 240" role="img" aria-label="${title}"><title>${title}</title>${body}</svg>`;
const text = (x,y,value) => `<text x="${x}" y="${y}" text-anchor="middle">${value}</text>`;
const ship = (x,y,color='var(--cyan)') => `<path d="M ${x} ${y-16} l 9 12 v 20 h -18 v -20 Z" fill="${color}"/>`;
const bars = (rows,max,unit) => `<div class="figure-bars">${rows.map(([name,value,kind=''])=>`<div class="figure-bar"><span>${name}</span><div class="figure-track"><i class="${kind}" style="width:${value/max*100}%"></i></div><b>${value.toLocaleString('de-DE')} ${unit}</b></div>`).join('')}</div>`;
export const styles = `
.controls label{min-width:0}
.teaching-figure{margin:28px 0 36px;padding:24px 0;border-top:1px solid var(--line);border-bottom:1px solid var(--line)}
.teaching-figure h3{margin:0 0 20px}.teaching-figure figcaption{font-size:14px;color:var(--muted);margin-top:18px;max-width:85ch}
.visual-flow{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:28px;list-style:none;padding:0;margin:0}
.visual-flow li{position:relative;padding:12px 0;border-top:3px solid var(--cyan)}.visual-flow li:not(:last-child)::after{content:'→';position:absolute;right:-23px;top:10px;color:var(--muted)}
.visual-flow strong,.visual-flow span{display:block}.visual-flow span{font-size:14px;color:var(--muted)}
.figure-pair .visual-flow{grid-template-columns:1fr}.figure-pair .visual-flow li:not(:last-child)::after{content:'↓';left:0;right:auto;top:auto;bottom:-29px}
.figure-pair{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:26px}.figure-pair h4{margin:0 0 12px;font-size:17px}.figure-pair p{font-size:15px}
.lesson-svg{display:block;width:100%;max-width:420px;height:auto;margin:0 auto;color:var(--ink)}.lesson-svg text{fill:currentColor;font:14px system-ui,sans-serif}.lesson-svg .wire{stroke:var(--line);stroke-width:1;fill:none}.lesson-svg .route{stroke:var(--cyan);stroke-width:2;fill:none}
.figure-bars{display:grid;gap:14px}.figure-bar{display:grid;grid-template-columns:100px minmax(0,1fr) 84px;gap:10px;align-items:center;font-size:14px}.figure-bar b{font-weight:500;text-align:right}.figure-track{height:16px;background:var(--line)}.figure-track i{display:block;height:100%;background:var(--cyan)}.figure-track i.candidate{background:var(--orange)}
.figure-note{color:var(--orange);font-size:14px}.network-sizes{display:grid;grid-template-columns:repeat(4,1fr);text-align:center;font-size:14px;gap:6px}.network-sizes strong{display:block;font-size:25px;color:var(--cyan)}
@media(max-width:650px){.figure-pair{grid-template-columns:1fr}.visual-flow{grid-template-columns:1fr}.visual-flow li:not(:last-child)::after{content:'↓';left:0;right:auto;top:auto;bottom:-29px}.figure-bar{grid-template-columns:84px minmax(0,1fr) 76px;font-size:13px}.teaching-figure{padding:20px 0}.network-sizes{font-size:12px}}
@media print{.teaching-figure{break-inside:avoid}.lesson-svg{color:black}.figure-track i{background:#366}.figure-track i.candidate{background:#986}.visual-flow span,.teaching-figure figcaption{color:#333}}
`;

function network() {
  const xs=[30,115,205,290], ys=[65,95,125,155,185];
  let drawing='';
  for(let layer=0;layer<3;layer++) for(const y of ys) for(const next of ys) drawing+=`<line class="wire" x1="${xs[layer]}" y1="${y}" x2="${xs[layer+1]}" y2="${next}"/>`;
  for(const x of xs) for(const y of ys) drawing+=`<circle cx="${x}" cy="${y}" r="7" fill="var(--cyan)"/>`;
  drawing+=text(30,32,'Eingabe')+text(115,32,'tanh')+text(205,32,'tanh')+text(290,32,'Logits');
  drawing+=text(160,223,'Jede Linie steht für ein Gewicht.');
  return svg('Vollständig verbundenes Netz: 37 Eingaben, zweimal 64 Neuronen, neun Logits. Gezeigt sind nur fünf Knoten je Schicht.',drawing);
}

export function figures(selection) {
  const baseline=selection.checks.final.baseline_summary, candidate=selection.checks.final.candidate_summary;
  const labels={aggressive:'Aggressiv',objective:'Auftrag',cautious:'Vorsichtig'};
  const rates = data => Object.entries(labels).map(([k,v])=>[v,Number((data[k].winRate*100).toFixed(2))]);
  return {
    m1:fig('diagram-hybrid','Wer entscheidet hier eigentlich?',flow([
      ['Sensorfilter · Regel','Gibt nur erlaubte Kontakte weiter.'],['Actor · gelernt','37 Werte → eine taktische Absicht.'],['Profil · Regel','Prüft Auftrag, Radar und Verhalten.'],['Planer · Regel','Berechnet Kurs und Waffenfreigabe.']
    ]),'Der trainierte Teil sitzt zwischen Wahrnehmung und Ausführung. Beim Spielen werden die Gewichte angewendet; neue Gewichte entstehen erst im Trainingslager.'),
    m2:fig('diagram-sensors','Ein Punkt ist mehr Wissen als eine Peilung',`<div class="figure-pair"><div><h4>Radar: präziser Kontakt</h4>${svg('Eigenes Schiff und präziser Zielpunkt innerhalb eines schematischen Radarkreises',`<circle class="wire" cx="160" cy="135" r="82"/>${ship(160,175)}<circle cx="205" cy="95" r="7" fill="var(--orange)"/><path class="route" d="M160 160 L205 95"/>${text(160,27,'Eigene Radarreichweite: 600 m')}${text(160,231,'Position und Zielzustand bekannt')}`)}</div><div><h4>ESM: Richtung eines Senders</h4>${svg('Eine ESM-Peilung passt zu mehreren Entfernungen entlang derselben Richtung',`${ship(65,185)}<path class="route" stroke-dasharray="6 5" d="M65 170 L250 45"/><circle class="wire" cx="120" cy="133" r="9"/><circle class="wire" cx="175" cy="96" r="9"/><circle class="wire" cx="230" cy="59" r="9"/>${text(160,27,'Mehrere mögliche Entfernungen')}${text(160,231,'Keine drei erkannten Schiffe!')}`)}</div></div>`,'Schematische Lehrgrafik, nicht maßstabsgetreu. Die leeren Kreise sind mögliche Orte desselben Senders. Eine reine Peilung verrät weder dessen genaue Entfernung noch HP oder Kurs.'),
    m3:fig('diagram-network','Das Netz als Rechenweg',`<div class="figure-pair"><div>${network()}<div class="network-sizes"><span><strong>37</strong>Features</span><span><strong>64</strong>Neuronen</span><span><strong>64</strong>Neuronen</span><span><strong>9</strong>Absichten</span></div></div><div><h4>Ein Neuron, Schritt für Schritt</h4>${flow([['1 · Gewichten','Jeder Eingang × sein Gewicht.'],['2 · Summieren','Alle Produkte + Bias.'],['3 · Aktivieren','tanh begrenzt auf −1 bis +1.']])}</div></div>`,'Knoten und Verbindungen sind zur Übersicht reduziert; Farben zeigen keine gemessenen Aktivierungen. Die letzte Schicht bleibt linear. Im Labor darunter rechnest du mit den echten 7.177 Actor-Parametern.'),
    m4:fig('diagram-reward','Gleiche Zeit, unterschiedliche Spielpunkte',bars([['Außerhalb',60],['Im Gebiet',300]],300,'Punkte'),'Vergleich für 60 Sekunden durchgehendes Überleben: 15 Vergaben à 4 bzw. 20 Punkte, ohne Abschüsse. Erst danach entstehen daraus Score-Reward und weitere Trainingsanteile. Spielpunkte und Trainingsreward haben unterschiedliche Einheiten.'),
    m5:fig('diagram-ppo','Der Kreislauf: handeln → bewerten → lernen',flow([['1 · Actor spielt','Zieht eine Aktion aus seiner Verteilung.'],['2 · Simulation','Liefert neue Beobachtung und Reward.'],['3 · Critic hilft','Erwartung und Ergebnis liefern Advantages.'],['4 · PPO-Update','Ändert Actor und Critic; dann neue Erfahrung sammeln.']])+`<div class="figure-pair"><p><strong>Vorwärts →</strong> Beobachtungen werden zu Aktionen und Wertschätzungen.</p><p><strong>← Rückwärts</strong> Backpropagation verteilt den Lernfehler auf die Netzgewichte.</p></div>`,'Der Critic wird beim Training gebraucht. Im Spiel reicht der exportierte Actor. Die Spielphysik wird nicht durchdifferenziert; sie liefert Erfahrungen für den nächsten Lernzyklus.'),
    m6:fig('diagram-intercept','Auf den Ort von jetzt oder den Ort beim Eintreffen?',`<div class="figure-pair"><div>${svg('Vorhalten: Ziel bewegt sich nach rechts, Flugkörper fliegt zum zukünftigen Treffpunkt',`${ship(60,175)}<circle cx="125" cy="65" r="8" fill="var(--orange)"/><circle cx="265" cy="65" r="8" fill="none" stroke="var(--orange)" stroke-width="2"/><path d="M140 65 H248 l-8 -5 m8 5 l-8 5" stroke="var(--orange)" fill="none"/><path class="wire" stroke-dasharray="5 5" d="M60 160 L125 65"/><path class="route" d="M60 160 L265 65"/>${text(125,40,'Ziel jetzt')}${text(263,96,'Treffpunkt')}${text(155,222,'Durchgezogen: vorausberechneter Weg')}`)}</div><div><h4>Zwei Wege, zwei Aufgaben</h4><p>Die gestrichelte Linie zeigt zur aktuellen Zielposition. Bewegt sich das Ziel weiter, kann der Schuss dahinter liegen.</p><p>Die durchgezogene Linie führt zum berechneten Treffpunkt. Das übernimmt unser Planer – die Absicht „Angreifen“ kommt vom Netz und den Profilregeln.</p></div></div>`,'Konstante Geschwindigkeiten und gerader Zielkurs als Lehrannahme; keine reale Flugbahnaufzeichnung. Ohne präzise Zielbewegung, etwa bei reiner ESM-Peilung, ist diese Abfanglösung nicht verfügbar.'),
    m7:fig('diagram-evaluation','Echte Messung: stärker ist nicht automatisch ausgewogener',`<div class="figure-pair"><div><h4>Bisherige Besetzung</h4>${bars(rates(baseline),100,'%')}</div><div><h4>Kandidat nach weiterem Training</h4>${bars(rates(candidate).map(([n,v])=>[n,v,'candidate']),100,'%')}</div></div><p class="figure-note">Siegquoten auf derselben Skala von 0 bis 100 %. Der neue Kandidat wurde nicht übernommen.</p>`,'Abschlusstest vom 01.10.2026: 120 Duelle je Besetzung, fünf Minuten, gleiche 20 Startseeds und vertauschte Seiten; 80 Teilnahmen pro Profil. Der Auftragsbot gewinnt häufiger, der unveränderte vorsichtige Bot verliert gegen den stärkeren Gegner häufiger. Quelle: balance-20261001/selection.json. Das ist ein anderer Test als die historische Tabelle darunter.'),
    m8:fig('diagram-experiment','Drei Datensätze, drei getrennte Aufgaben',flow([['Training','Verändert die Gewichte.'],['Validierung','Wählt unter den Checkpoints aus.'],['Frischer Abschlusstest','Prüft die zuvor festgelegte Auswahl.']]),'Wer nach dem Abschlusstest weiter an der Auswahl feilt, braucht anschließend neue Teststarts. Sonst wird aus dem Test unbemerkt ein Teil der Optimierung.')+
    fig('diagram-cooperation','Ausblick: Kooperation gegen einen stärkeren Gegner',`<div class="figure-pair"><div>${svg('Geplantes Teamtraining: zwei eigene Bots nähern sich einem stärkeren Gegner aus verschiedenen Richtungen',`<circle cx="160" cy="118" r="83" class="wire"/>${ship(160,65,'var(--orange)')}${ship(65,180)}${ship(255,180)}<path class="route" stroke-dasharray="6 5" d="M70 155 Q80 92 145 80 M250 155 Q240 92 175 80"/>${text(160,26,'Stärkerer Gegner')}${text(65,226,'Bot A')}${text(255,226,'Bot B')}`)}</div><div><h4>Noch nicht implementiert</h4><p>Beide Bots handeln mit ihren erlaubten Beobachtungen. Gemeinsame Erfolge könnten beide Policies belohnen.</p><p>Unterschiedliche Rollen: Einer setzt den Gegner unter Druck, der andere unterstützt aus Abstand. Solches Verhalten müsste erst trainiert und geprüft werden.</p><p>Geteilte Kontakte erfordern eine ausdrücklich definierte Kommunikationsregel.</p></div></div>`,'Konzeptskizze, keine gemessene Kooperation der aktuellen Bots. Zwei gegen einen zu gewinnen genügt als Nachweis nicht: Wir müssten mit zwei ebenso starken Bots ohne Kooperation vergleichen.')
  };
}
