import assert from "node:assert/strict";
import { createLazyResource } from "./lazyResource";
let loads = 0;
let disposed = 0;
let resolve!: (value: { dispose(): void }) => void;
const lazy = createLazyResource(() => { loads++; return new Promise<{ dispose(): void }>((r) => { resolve = r; }); });
assert.equal(loads, 0);
assert.equal(lazy.get(), null);
const first = lazy.ensure();
assert.equal(lazy.ensure(), first);
assert.equal(loads, 1);
lazy.dispose();
resolve({ dispose() { disposed++; } });
assert.equal(await first, null);
assert.equal(disposed, 1);
assert.equal(await lazy.ensure(), null);
lazy.dispose();
assert.equal(disposed, 1);
let attempts = 0;
const retry = createLazyResource(async () => {
  if (++attempts === 1) throw new Error("load failed");
  return { dispose() { disposed++; } };
});
await assert.rejects(retry.ensure(), /load failed/);
assert(await retry.ensure());
assert.equal(attempts, 2);
retry.dispose(); retry.dispose();
assert.equal(disposed, 2);
console.log("lazy optional UI lifecycle tests ok");
